export { default as ExternalLinkSvg } from './external-link.svg'
export { default as FigmaSvg } from './figma.svg'
export { default as GithubSvg } from './github.svg'
export { default as LinkedinSvg } from './linkedin.svg'
export { default as MailSvg } from './mail.svg'
export { default as PackageSvg } from './package.svg'
export { default as TwitterSvg } from './twitter.svg'
